### ISSUE TITLE
Request for scanning new channels EPG for canalplus.com France

### ISSUE THREAD

**Issue by Talon555** [iptv-org/epg#1102]
Hello

By scanning their EPG sourcing, many new channels could be add

For :

https://www.canalplus.com/programme-tv/

https://github.com/iptv-org/epg/tree/master/sites/canalplus.com

Please

**Comment by freearhey** [comment]
Please specify the name of the channels that are missing so we can help you.

**Comment by LaneSh4d0w** [comment]
I know we've added Canal + Sport 360 and Canal + Foot recently. There's channels like Nick Ukraine that are also on MyCanal (or Canal + in general), if that's the reference you're expecting.

**Comment by Talon555** [comment]
Canal+ Grand Ecran
Canal+ DOCS 
Canal+ KIDS
Canal+ MOTO GP 
Canal+ FORMULA 1 
Canal+ PREMIER LEAGUE 
Canal+ TOP 14 
Canal+ Sport 360
Canal+ Foot
DISNEY+
NETFLIX
STARZPLAY

**Comment by RevGear** [comment]
Canal+ Grand Ecran - CanalPlusGrandEcran.fr
Canal+ DOCS - CanalPlusDocs.fr
Canal+ KIDS - CanalPlusKids.fr
Canal+ MOTO GP - CanalPlusMotoGP.fr
Canal+ FORMULA 1 - CanalPlusFormula1.fr
Canal+ PREMIER LEAGUE - CanalPlusPremierLeague.fr
Canal+ TOP 14 - CanalPlusTop14.fr
Canal+ Sport 360 - CanalPlusSport360.fr
Canal+ Foot - CanalPlusFoot.fr
Already in the channels xml

DISNEY+
NETFLIX
STARZPLAY
Aren't these streaming services rather than liner channels? If so there won't be an EPG.

**Comment by LaneSh4d0w** [comment]
> Canal+ Grand Ecran - CanalPlusGrandEcran.fr Canal+ DOCS - CanalPlusDocs.fr Canal+ KIDS - CanalPlusKids.fr Canal+ MOTO GP - CanalPlusMotoGP.fr Canal+ FORMULA 1 - CanalPlusFormula1.fr Canal+ PREMIER LEAGUE - CanalPlusPremierLeague.fr Canal+ TOP 14 - CanalPlusTop14.fr Canal+ Sport 360 - CanalPlusSport360.fr Canal+ Foot - CanalPlusFoot.fr Already in the channels xml
> 
> DISNEY+ NETFLIX STARZPLAY Aren't these streaming services rather than liner channels? If so there won't be an EPG.

They are, though Canal + has made a "channel" that redirects to the streaming service's specific page made for this occasion.
