### ISSUE TITLE
Combined Guide Enhancement Request

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1217]
### Guide

https://iptv-org.github.io/epg/guides/uk_en.xml

### Description

While the new combined guides (Patch 2022.10.4 #1212), in theory, make things simpler, is it possible to look at the priority order of the previous guides?

For example; for UK channels, when using the previous guides, I can set the priority in tivimate, so it will first use Sky, then BT, then Virgin for any channels not covered by the first one in the list. But when using the combined guide, I now get long strings after the programme description like series/episode number, which for channels such as BBC News is pretty much useless. I suspect it's picking these up from the Virgin guide, as I've previously only got this on BBC One Northern Ireland.

Not sure if I've explained that clearly. But basically, if the combined guides are all that is going to be available in future, I think the order needs to be defined with the "best" ie, "cleanest" guide first.

**Comment by hehewtf** [comment]
bt sport 4 is in the us.xml btw

**Comment by mcastellaneta** [comment]
Exactly, or at least talk about how the prioritization score should be calculated. 
As I understand it, the score is calculated on each program based on this code.
https://github.com/iptv-org/epg/blob/8457ca79d274f16dd79e951bf0590aa5a53a57d7/scripts/commands/guides/update.js#L163-L177
and then the site with the highest sum of programs scores is chosen.

But I am having trouble understanding exactly how it works, because in today's Italian guide there is an alternation of sources, although both guides contain all the channels.

![it](https://user-images.githubusercontent.com/43062263/200184258-98aed95d-2687-4d67-a7d7-ab33ac1d5d84.png)

**Comment by freearhey** [comment]
In general @mcastellaneta described everything absolutly right and for each channel is already selected the "best" available sources based on the amount of information it has about each program. In addition, when selecting a source also takes into account the official language of the country for which the guide compiled so that the French guide does not have descriptions in Chinese.

However, if any errors do appear in the future they can still be fixed by editing the appropriate config as @RevGear showed in #1240.
