### ISSUE TITLE
some channels notes

### ISSUE THREAD

**Issue by Shawkiiz** [iptv-org/epg#1430]
### Channel ID

Eg.xml

### Source

https://iptv-org.github.io/epg/guides/eg.xml

### Notes

Thx bro for updating most chaneels icon 🌹
And here's some channels notes ☺️

- Al hayat > no icon
- Al hayat drama > no epg
- cbc sofra > no icone 
- al kahera walnas (2) > no epg
- etc > no epg
- all pnc > no epg 
- rotana aflam plus > no epg

Thx bro for support 🙏🏻

**Comment by Shawkiiz** [comment]
its wrong icon for "Al hayat" , the correct one is ( https://media0001.elcinema.com/tvguide/1137_2.png )

**Comment by freearhey** [comment]
The logos of Alhayat TV and CBC Sofra were updated (https://github.com/iptv-org/database/commit/1aed3ee10bfc7e7dd296048303ab1c886bf30321)

And program for

- Alhayat TV
- Al Kahera Wal Nas 2
- ETC TV

 is added to https://iptv-org.github.io/epg/guides/eg.xml

The remaining channels cannot be added because there is no source for them yet

If you find one, let us know through this [form](https://github.com/iptv-org/epg/issues/new?assignees=&labels=%F0%9F%97%93+epg+request&template=----epg-request.yml)

**Comment by Shawkiiz** [comment]
Thx for support ❤️

Sure If i find any new i'll contact u 👍🏻
