### ISSUE TITLE
JOJ Family

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1463]
### Source

https://jojfamily.blesk.cz/tv-program

### Channels

JOJ Family - JOJFamily.sk

**Comment by PopeyeTheSai10r** [comment]
JOJ Family is included in https://github.com/iptv-org/epg/blob/gh-pages/guides/cz/m.tv.sms.cz.epg.xml

**Comment by PopeyeTheSai10r** [comment]
> Doesn't seem to be working. All I get is 'No information'. All other JOJ channels have EPG info.

Can you please make that the NAME and/or TVG-ID matches what your playlist is using?

**Comment by PopeyeTheSai10r** [comment]
Can you try using a different player to see if the results are the same?

Perhaps trying one of [web players](https://github.com/iptv-org/awesome-iptv#web)

**Comment by Smark223** [comment]
Exactly the same. The database https://iptv-org.github.io/ doesn't show the channel as having a valid EPG source, so I think there's definitely something not right.

**Comment by PopeyeTheSai10r** [comment]
Ok, sounds like this will require a new config for the source linked.

**Comment by RevGear** [comment]
I think the issue is to do with how the new combined guides are created. 
JOJ Family is in the database with a broadcast country of Slovakia and the database only lists Slovak as the official language of Slovakia. The data created by m.tv.sms.cz.epg.xml is in Czech, which means it will not get picked up for the combined guides. 

All the other JOJ channels in the guide are sourced from horizon.tv, which is in the Slovak language. Assuming it's available, adding JLOJ Family to horizon.tv should fix the issue.

**Comment by Smark223** [comment]
Thanks for looking into that @RevGear

**Comment by m1k1o** [comment]
> the database only lists Slovak as the official language of Slovakia

I fixed this already in https://github.com/iptv-org/database/pull/1585.

JOJ Family is only meant for CZ, along with following channels:
- Broadcast area for SK: `NovaInternational.cz`, `PrimaPlus.cz`
- Broadcast area for CZ: `MarkizaInternational.sk`, `JOJFamily.sk`

I'll be fixing them soon in the database.

**Comment by freearhey** [comment]
The guide for JOJ Family is now available at these links:

- `https://iptv-org.github.io/epg/guides/cs/m.tv.sms.cz.xml`
- `https://iptv-org.github.io/epg/guides/sk/mujtvprogram.cz.xml`
