### ISSUE TITLE
TH: epg source

### ISSUE THREAD

**Issue by Dum4G** [iptv-org/epg#15]
https://tv.trueid.net/tvguide/all/

**Comment by freearhey** [comment]
I created a [script](https://github.com/iptv-org/epg/blob/add-guide-from-tv-trueid-net/sites/tv.trueid.net.config.js) for this site, but unfortunately in the process it turned out that the site is very unstable (in most cases the server can not return any response), so until that changes I can not add it to the list.

**Comment by LaneSh4d0w** [comment]
It's also because this website is loooooooong to load. So many things that goes in the process. Best would be simply to get a sort of JSON or something to facilitate the process. I think you can get the EPG in JSON by actually faking a live stream request.
