### ISSUE TITLE
Multiple epg file

### ISSUE THREAD

**Issue by melbasuonyy** [iptv-org/epg#1517]
### Description

Since full list of guides is not possible due to size limitations what about selecting multiple sources and creat a file if possible i think it will be helpful 
Thanks

**Comment by juniorpainkiller** [comment]
That would be great. I'm struggling to create multiple EPG.

**Comment by RevGear** [comment]
EPGs are not created dynamically, the files are rebuilt overnight. That means the process would have to know which files to combine at that point. The problem is that the files you want combined may not be the same as the ones I would like combined, which may not be the same as the files someone else wants combining. There could be thousands of possible combinations; it would be simply impossible to create them all.

**Comment by benbelgium** [comment]
I will be writing an app to do exactly that! Also with 'service' option so this is done daily at a scheduled time.

**Comment by benbelgium** [comment]
![image](https://user-images.githubusercontent.com/43570427/209168763-0cf596d1-dcaf-46f4-a0d1-34001dee22c1.png)
I'm getting there... still sorting out some minor problems, making it prettier and adding new features.... hang in there...

**Comment by freearhey** [comment]
As @RevGear rightly pointed out we cannot implement this feature in the scope of this repository, so I can only advise you to look for a player that allows you to automatically merge the program from multiple files (such as [IPTV Merge Kodi Add-on](https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html), [GSE Smart IPTV](https://gsesmartiptv.com/), etc).

@benbelgium when you finish developing your app you can post a link to it at [iptv-org/awesome-iptv](https://github.com/iptv-org/awesome-iptv).

**Comment by benbelgium** [comment]
@melbasuonyy and @juniorpainkiller : it's available at www.bevy.be
@freearhey : it's requested in awesome-iptv

thanks

Ben

**Comment by K-vanc** [comment]
hi @freearhey , this is K-vanc the author of Tempest Epg Generator, another free epg generator script hosted on github. I dont know who is in charge of this repo but I just wanted to highlight that this guy @benbelgium is using my generator and siteconfiguration files and hosting generated files on his mentioned website after editing generator information such as done by his probably unreal tool. I dont know if this kind of things are welcomed in your repo since as far as I know, you are generating and hosting your own epg with your own tool and source configuration files, but in my place this is called "robbery".

So it is under your consideration to decide how.

Note: I have also tons of requests mails from him while trying to help him and can share privately if you need

**Comment by freearhey** [comment]
> Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

https://github.com/iptv-org/epg/blob/master/LICENSE
