### ISSUE TITLE
beIN Sports English EPGs incorrect

### ISSUE THREAD

**Issue by Smark223** [iptv-org/epg#1583]
### Guide

https://iptv-org.github.io/epg/guides/qa.xml

### Description

Guides for beIN Sports 1, 2 and 3 English are incorrect. Not sure where the combined guide is picking the EPG up from but it's correct in https://www.bein.com/en/tv-guide/?c=gb which I believe is the source for https://github.com/iptv-org/epg/blob/master/sites/bein.com/bein.com_qa.channels.xml 
However, it seems to be picking up data that doesn't correspond with what's on.

**Comment by Smark223** [comment]
Just trying to investigate further and it appears beIN Sports English 1 is showing the EPG for beIN Sports English 2 and beIN Sports English 2 is showing the EPG for beIN Sports English 3. beIN Sports English 3 is *I think* showing the EPG for beIN Sports French 1, so it suggests a formatting issue.

It's more difficult to work out as EPG seems to be timeshifted by 6 hours, which I can fix locally but EPG info needs allocating to the correct channels.

**Comment by sunuazizrahayu** [comment]
other reference about bein sports english here -> https://beinsports.com/en/tv-guide

**Comment by RevGear** [comment]
The issue is that beinsports.com channel xml files don't really use static site_ids, they are more sequential numbers. An id of "19" just means get the 19th channel returned from the data source. BeIN occasionally add/move channels. Were were looking for beIn Sport English 1/2/3 to be the 19th/20th/21st channels but they are now 18/19/20th
