### ISSUE TITLE
Puerto Rican channel listings are one hour ahead

### ISSUE THREAD

**Issue by ehzzzd** [iptv-org/epg#1879]
### Guide

https://iptv-org.github.io/epg/guides/es/gatotv.com.xml

### Description

The information of the programs are one hour ahead. It shows what's coming next instead of what is currently on the air.

Channels:
WKAQ (DT1, DT2), WAPA (DT1, DT2), WORO, WRUA

**Comment by RevGear** [comment]
Is it just those channels or everything in that file?

All the data scrapped is in local time, which we assume to be EST and convert to UTC. I'm guessing these are in Puerto Rican local time (AST) which is an hour different to EST.

**Comment by hernandez756** [comment]
I think it's just those channels and yes, the Puerto Rican channels are supposed to be in AST. But it could also be some of the other channels in the file, since Canal 1's schedule (Canal1.co) is also having the same issue

**Comment by PopeyeTheSai10r** [comment]
This is a problem across multiple sources: tvpassport, ontvtonigh and gatotv. They are all off by 1 hour. [Telemundopr.com](https://www.telemundopr.com/entretenimiento/entretenimiento-destacados/programas-4/2046238/) has the correct timing but only partial guide.

I think the issue here is that the sources are not accounting for Puerto Rico not observing daylight saving like the rest of America.

**Comment by PopeyeTheSai10r** [comment]
#1924 doesn't fix this issue.

**Comment by PopeyeTheSai10r** [comment]
Closing since the repo no longer provides pre-made guides and this is an issue with the sources, not the grabber.
