### ISSUE TITLE
FLIXED TV GUIDE 

### ISSUE THREAD

**Issue by Kamiela20100** [iptv-org/epg#1906]
### Guide

https://iptv-org.github.io/epg/guides/en/flixed.io.xml

### Description

Every channel throwing No Info in Tivimate

**Comment by freearhey** [comment]
The guide works fine, but due to the limitations of the flixed.io API, we can't load the programs for more than one day. As a result, the guide cuts off at 0:00 UTC.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/7253922/215526595-c3debba0-d26c-4c57-a44b-7a9e4d580792.png">

And until their API changes we can hardly do anything about it.
