### ISSUE TITLE
Optus Sport

### ISSUE THREAD

**Issue by francisuk1989** [iptv-org/epg#1988]
### Source

> https://sport.optus.com.au/api/sportsdata/

### Notes
The URL gives a JSON however someone has made this to work in PHP
`http://webgrabplus.com/content/optus-sport`

**Comment by RevGear** [comment]
Data is laid out as a match schedule rather than a conventional programme list. You can at least get the channel number. There's a match start time, which may not be the actual broadcast start time, but no end time or duration. It isn't a normal channel with a continuous broadcast and filler programmes between the live events, so we can't use the start time of one programme to be the end time of the previous programme. Previous programme may have ended hours earlier or even the previous day. We could just assume every programme is 2(?) hours long, but that's probably going to raise a lot of queries.
