### ISSUE TITLE
Movistar Plus Spain EPG?

### ISSUE THREAD

**Issue by MILO123PRO** [iptv-org/epg#2056]
### Description

Hi, while inspecting ver.movistarplus.es, i noticed an URL that i think that is an EPG, can you guys tell me what it is? and if it is an EPG, add it, it has like 50+ channels i think:
https://ottcache.dof6.com/movistarplus/webplayer/OTT/contents/channels?mdrm=true&tlsstream=true&demarcation=15&version=8

I think that the parameters of mdrm, tlsstream, demarcation and version can be modified.

**Comment by PopeyeTheSai10r** [comment]
Hello, We should have a working config for Movistar Plus Spain. You should navigate to https://github.com/iptv-org/epg/tree/master/sites/movistarplus.es.

 We are no longer able to provide pre-made guides due to the disabling of GitHub Actions but you can always clone the repo and run the grabber locally by following https://github.com/iptv-org/epg#how-to-use

**Comment by MILO123PRO** [comment]
@PopeyeTheSai10r  I mean that the link i sended maybe its useful for iptv-org

**Comment by freearhey** [comment]
@MILO123PRO The link contains a list of channels with descriptions. There is no program guide.

**Comment by MILO123PRO** [comment]
Oh ok.
