### ISSUE TITLE
tvpassport.com fails to save the guide

### ISSUE THREAD

**Issue by marianpopeanga** [iptv-org/epg#2175]
### Site

tvpassport.com

### Description

This guide takes very long time to complete and now it fails just before completion: 

/volume1/home/marian/lucru/epg/scripts/commands/epg/grab.js:192
      let programLang = program.titles[0].lang
                                          ^

TypeError: Cannot read properties of undefined (reading 'lang')
    at save (/volume1/home/marian/lucru/epg/scripts/commands/epg/grab.js:192:43)
    at runJob (/volume1/home/marian/lucru/epg/scripts/commands/epg/grab.js:88:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/volume1/home/marian/lucru/epg/scripts/commands/epg/grab.js:52:5)****

**Comment by Sicilykill** [comment]
I was seeing a similar issue with a different site,  gatotv.com
In this case the problem was with a specific channel where the titles object was null.
To identify the channel, you can add the following before line 192 of `/epg/scripts/commands/epg/grab.js`

```
if ( program.titles[0] == null )
        logger.info( JSON.stringify(program))
```

If you then run the npm grab it should output the channel that is missing the data.
While this does not solve your issue it can at least help identify which channel is causing the problem. 
I hope it helps.

**Comment by freearhey** [comment]
Fixed in https://github.com/iptv-org/epg/pull/2177

Please try to [update](https://github.com/iptv-org/epg?tab=readme-ov-file#update) or [reinstall](https://github.com/iptv-org/epg?tab=readme-ov-file#installation) the grabber.
