### ISSUE TITLE
Directv epg not showing discription of the show and missing some channels

### ISSUE THREAD

**Issue by TheDeatCrusher** [iptv-org/epg#360]
There is a issue with the directv epg it diesn't show a discription of the show on the guide and there isn't abc fox nbc or cbs epgs on the directv url it would be apprecisted if you fixed this

**Comment by freearhey** [comment]
Please stop spamming (https://github.com/iptv-org/epg/issues/318)

**Comment by TheDeatCrusher** [comment]
Can you just fix this i have gotten no response at all that's all i ask

**Comment by freearhey** [comment]
The program descriptions should appear in the guide tomorrow.

As for the new channels, you will have to clarify which channels you are talking about, because each channel has many versions. Or you can add the channels you want to the list yourself: https://github.com/iptv-org/epg/blob/master/sites/directv.com/directv.com_us.channels.xml

**Comment by TheDeatCrusher** [comment]
I would do it but i don't know were to start
