### ISSUE TITLE
I've constructed the xml but need to create the config file

### ISSUE THREAD

**Issue by TertoGordez** [iptv-org/epg#536]
Hi,

I've constructed an XML file for the Swedish site TV.nu, but I need help from someone to create the config file. My XML file contains about the double amount of channels compared to the existing Swedish list (Allente). 

File structure is:
<?xml version="1.0" encoding="UTF-8"?>
<site site="tv.nu">
  <channels>
    <channel lang"sv" xmltv_id="" site_id=""></channel>
    ....
  </channels>
</site>

xmltv_id are from : https://iptv-org.github.io/ (channels that were not found were removed from my file)
site_id are taken from : webgrabplus . com

Is there someone that could help out? 
Here is my txt file: [tv.nu_se.channels.txt](https://github.com/iptv-org/epg/files/8133505/tv.nu_se.channels.txt)

**Comment by LaneSh4d0w** [comment]
From https://www.tv.nu/alla-tv-kanaler.

Logos are represented by the logotyp alt, grabbing them by their source should work.
Channel names are inside some aria-label.

The trickiest part would be to get the EPG off it, since it basically is a React generated page it seems, so all IDs are generated too.
Program that's being shown on TV right now seems to have class name _2XxJl, others seem to have _3iB12.
Time is given as datetime, name is given inside _1fvq6

**Comment by TertoGordez** [comment]
Within the .ini file i got that api is https://web-api.tv.nu

Here is the .ini file (converted to txt to be able to upload) from webgrabber:[tv.nu.txt](https://github.com/iptv-org/epg/files/8180209/tv.nu.txt)

don't know if it helps in any way....

**Comment by LaneSh4d0w** [comment]
> Within the .ini file i got that api is https://web-api.tv.nu
> 
> Here is the .ini file (converted to txt to be able to upload) from webgrabber:[tv.nu.txt](https://github.com/iptv-org/epg/files/8180209/tv.nu.txt)
> 
> don't know if it helps in any way....

Thank you.

24hr it seems.

https://web-api.tv.nu/channels/ *channelID* /schedule?date= *date (is generated by moment)* &fullDay=true

**Comment by freearhey** [comment]
The guide is available at:

```
https://iptv-org.github.io/epg/guides/se/tv.nu.epg.xml
```
