### ISSUE TITLE
programetv.ro.epg.xml pulling EPG from the past only?

### ISSUE THREAD

**Issue by benevenstanciano** [iptv-org/epg#837]
I'm not sure where the issue lies but I can see in the XML that channels are only pulling historic guide data. I can't see in the code what exactly is happening. Does anyone have any ideas?

**Comment by mcastellaneta** [comment]
The code gets the current day and maps it as a number from 0 (Sunday) to 6 (Saturday). 
https://github.com/iptv-org/epg/blob/e78200556d1c3fac3e684e8c59c367faf46bca60/sites/programetv.ro/programetv.ro.config.js#L15
that is used as position in array _daysOfWeek_ 
https://github.com/iptv-org/epg/blob/e78200556d1c3fac3e684e8c59c367faf46bca60/sites/programetv.ro/programetv.ro.config.js#L6-L14
to create the final URL
https://github.com/iptv-org/epg/blob/e78200556d1c3fac3e684e8c59c367faf46bca60/sites/programetv.ro/programetv.ro.config.js#L17
I think that the array does not represent the 7 days names, because 'ieri' and 'azi' are not days names, but 'yesterday' and 'today' (according to translators).

**Comment by benevenstanciano** [comment]
Ah yes, that makes sense. Replacing 'ieri' with 'miercuri' and 'azi' with 'joi' makes it work, I've tested with the URLs. I've submitted https://github.com/iptv-org/epg/pull/838 to fix this. Thanks for finding out the issue!
