### ISSUE TITLE
Fix: BeIN Sports English (Qatar) 

### ISSUE THREAD

**Issue by Dr3sdan** [iptv-org/epg#999]
### Describe your issue

Qatar -  BeIN Sports English all Epgs in the Qatar section are either, not working or are showing a different epg

**Comment by RevGear** [comment]
The script doesn't use channel ID but rather counts down the list of channel details. I did a change recently because Bein Sport Xtra 2 had disappeared meaning that the channels below that we out of synch. Eg BeIn NBA was expecting to be the 13th channel in the data but was actually the 12th. Bein Sport Xtra 2 is now back as the 11th channel meaning everything below it was out of synch again. I'll revert the previous change.
